<?php
/*
 * @file
 * implements hook theme
 */
/**
 * Implements hook_theme().
 */
function pizza_theme($existing, $type, $theme, $path) {
  return [
'pizza-form'=>[
  'render element'=> 'form',
],
    'current_user'=>[
      'variables'=>[
        'user'=>NULL
      ],
    ],
  ];

}

/**
 * Implements hook_theme_suggestions_HOOK().for current_user
 */
function pizza_theme_suggestions_current_user(array $variables) {
  $variables['user'] = Drupal::currentUser()->isAuthenticated();
  if( $variables['user']){
    print_r(Drupal::currentUser()->id());
  }
}
